/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capturadefotos;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aluno
 */
public class capturaFotos extends javax.swing.JPanel {
    VideoCaptura webCam;
    ExibeQuadro exibeQuadro;
    Thread executor;
    /**
     * Creates new form capturaFotos
     */
    public capturaFotos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtSalvar = new javax.swing.JButton();
        jbtIniciar = new javax.swing.JButton();
        jbtParar = new javax.swing.JButton();
        frameDeCaptura = new javax.swing.JScrollPane();
        jlbCaptura = new javax.swing.JLabel();

        jbtSalvar.setBackground(new java.awt.Color(1, 87, 155));
        jbtSalvar.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jbtSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jbtSalvar.setText("SALVAR FOTO");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtIniciar.setBackground(new java.awt.Color(1, 87, 155));
        jbtIniciar.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jbtIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jbtIniciar.setText("INICIAR");
        jbtIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIniciarActionPerformed(evt);
            }
        });

        jbtParar.setBackground(new java.awt.Color(1, 87, 155));
        jbtParar.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jbtParar.setForeground(new java.awt.Color(255, 255, 255));
        jbtParar.setText("PARAR");
        jbtParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPararActionPerformed(evt);
            }
        });

        frameDeCaptura.setPreferredSize(new java.awt.Dimension(646, 485));

        jlbCaptura.setPreferredSize(new java.awt.Dimension(300, 250));
        frameDeCaptura.setViewportView(jlbCaptura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtIniciar)
                        .addGap(101, 101, 101)
                        .addComponent(jbtParar)
                        .addGap(252, 252, 252)
                        .addComponent(jbtSalvar))
                    .addComponent(frameDeCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(frameDeCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtParar)
                    .addComponent(jbtIniciar)
                    .addComponent(jbtSalvar)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        try {
            webCam.salvarFoto();
        } catch (IOException ex) {
            Logger.getLogger(capturaFotos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIniciarActionPerformed
        webCam = new VideoCaptura();
        exibeQuadro = new ExibeQuadro(webCam, jlbCaptura);
        executor = new Thread(exibeQuadro);
        executor.start();
        jbtSalvar.setEnabled(false);
    }//GEN-LAST:event_jbtIniciarActionPerformed

    private void jbtPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPararActionPerformed
        executor.suspend();
        jbtSalvar.setEnabled(true);
    }//GEN-LAST:event_jbtPararActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane frameDeCaptura;
    private javax.swing.JButton jbtIniciar;
    private javax.swing.JButton jbtParar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JLabel jlbCaptura;
    // End of variables declaration//GEN-END:variables
}
