/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.UIManager;
import javax.swing.plaf.ScrollBarUI;

/**
 *
 * @author Aluno
 */
public class SaibaMais extends javax.swing.JPanel {

    /**
     * Creates new form SaibaMais
     */
    public SaibaMais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 87, 155));
        jLabel1.setText("Colaboradores");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setText("Pessoas que tornaram esse projeto viável");

        scroll.setBorder(null);

        jTextPane2.setContentType("text/html"); // NOI18N
        jTextPane2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextPane2.setText("<html>\n<body>\n<font face=\"Trebuchet MS\" size=\"5\">\n<b>Professores</b><br>\nJosé Wilson\nWilliam Sallum<br><br>\n<b>Gerência</b><br>\nAdalberto Barbosa\nJoão Pedro Rosa\nPaula Ribeiro\nVitor Rodarte<br><br>\n<b>Modelo de Provas/Trabalhos</b><br>\nVictor César\nGabriel Victor\nIsabela Carolina\nJoão Pedro dos Santos<br><br>\n<b>Fórum</b><br>\nVictor Gabriel\nLuana Pinheiro\nMatheus Morato\nRafael Gontijo<br><br>\n<b>Download/Upload Aplicativos</b><br>\nPedro Otávio\nAndré Mateus\nBruno Ferreira<br><br>\n<b>Correção Provas e Trabalhos</b><br>\nLuiz Augusto\nFelipe Linhares\nLucas Henrique<br><br>\n<b>Mural</b><br>\nGabriel Haddad\nBreno Mariz\nBryann Bueno<br><br>\n<b>Chat</b><br>\nCarlos Eduardo\nAna Luísa Menezes\nEster Atman<br><br>\n<b>Repositório de Fotos</b><br>\nMarcelo Augusto\nMaria Carolina Resende\nThales Alan Araújo\nGabriel Garcia<br><br>\n<b>Banco de Questões</b><br>\nJoão Vitor de Carvalho\nBreno Paiva\nThales Gabriel Nunes\nAlice Costa<br><br>\n<b>Calendário</b><br>\nPedro Henrique Almeida\nGabriel Vinícius\nAmaury Vianna\n</font>\n</body>\n</html>\n");
        scroll.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(scroll)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
