/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import bancodequestoes.ConexaoBD;
import bancodequestoes.EscreveXML;
import bancodequestoes.ProvaEspecifica;
import bancodequestoes.ProvaGenerica;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Paiva Morais
 */
public class Gerar extends javax.swing.JFrame {

    /**
     * Creates new form Gerar
     */
    public Gerar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        homeGerar = new javax.swing.JButton();
        disciplinaGerar = new javax.swing.JComboBox<>();
        temaGerar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        enviarGerar = new javax.swing.JButton();
        nQuestoesGerar = new javax.swing.JSlider();
        facilGerar = new javax.swing.JCheckBox();
        medianaGerar = new javax.swing.JCheckBox();
        dificilGerar = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numDiserta = new javax.swing.JLabel();
        numME = new javax.swing.JLabel();
        numVF = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1028, 650));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 87, 155));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Banco de Questões");
        jLabel7.setToolTipText("Banco de Questões");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setAlignmentX(0.5F);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setAutoscrolls(true);

        homeGerar.setBackground(new java.awt.Color(33, 150, 243));
        homeGerar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        homeGerar.setForeground(new java.awt.Color(255, 255, 255));
        homeGerar.setText("HOME");
        homeGerar.setToolTipText("Ir para inicio");
        homeGerar.setAlignmentX(0.5F);
        homeGerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeGerarActionPerformed(evt);
            }
        });

        disciplinaGerar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        disciplinaGerar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina a disciplina:", "Aplicações para Web", "Arquitetura de Sistemas Digitais", "Linguagem de Programação - JAVA", "Manutenção de Computadores", "Biologia", "Filosofia", "Física", "Geografia", "História", "Matemática", "Português", "Química", "Sociologia", "Outra" }));
        disciplinaGerar.setToolTipText("Defina a disciplina da questão");

        temaGerar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        temaGerar.setForeground(new java.awt.Color(153, 153, 153));
        temaGerar.setText("DIGITE O TEXTO AQUI.");
        temaGerar.setToolTipText("Defina a tema");
        temaGerar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                temaGerarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temaGerarFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Defina o estilo e dificuldade das questões da prova:");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Digite os temas (separados por virgula):");
        jLabel9.setToolTipText("Defina o tema");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Defina o número de questões: 50");
        jLabel11.setToolTipText("Defina o número de questões");

        enviarGerar.setBackground(new java.awt.Color(33, 150, 243));
        enviarGerar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enviarGerar.setForeground(new java.awt.Color(255, 255, 255));
        enviarGerar.setText("GERAR");
        enviarGerar.setToolTipText("Gerar a prova");
        enviarGerar.setActionCommand("");
        enviarGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarGerarActionPerformed(evt);
            }
        });

        nQuestoesGerar.setBackground(new java.awt.Color(255, 255, 255));
        nQuestoesGerar.setForeground(new java.awt.Color(0, 0, 0));
        nQuestoesGerar.setMajorTickSpacing(10);
        nQuestoesGerar.setMinorTickSpacing(1);
        nQuestoesGerar.setPaintLabels(true);
        nQuestoesGerar.setPaintTicks(true);
        nQuestoesGerar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nQuestoesGerarStateChanged(evt);
            }
        });
        nQuestoesGerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nQuestoesGerarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nQuestoesGerarMousePressed(evt);
            }
        });

        facilGerar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        facilGerar.setForeground(new java.awt.Color(153, 153, 153));
        facilGerar.setText("Fácil");
        facilGerar.setToolTipText("Acresentar questões faceis na prova");

        medianaGerar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        medianaGerar.setForeground(new java.awt.Color(153, 153, 153));
        medianaGerar.setText("Mediana");
        medianaGerar.setToolTipText("Acresentar questões Medianas na prova");

        dificilGerar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dificilGerar.setForeground(new java.awt.Color(153, 153, 153));
        dificilGerar.setText("Difícil");
        dificilGerar.setToolTipText("Acresentar questões difíceis na prova");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Dissertativas");
        jLabel1.setToolTipText("Numero de dissertativas na prova");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Múltipla Escolha");
        jLabel2.setToolTipText("Numero de multipla escolha na prova");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Verdadeiro ou Falso");
        jLabel3.setToolTipText("Numero de verdadeiro ou falso na prova");

        numDiserta.setText("?");
        numDiserta.setToolTipText("Numero de dissertativas na prova");

        numME.setText("?");
        numME.setToolTipText("Numero de Dissertativas na prova");

        numVF.setText("?");
        numVF.setToolTipText("Numero de verdadeiro ou falso na prova");

        jButton2.setBackground(new java.awt.Color(33, 150, 243));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("-");
        jButton2.setToolTipText("Subtrair dissertativas na prova");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(33, 150, 243));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+");
        jButton1.setToolTipText("Acresentar dissertativas na prova");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(33, 150, 243));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("-");
        jButton3.setToolTipText("Subtrair multipla escolha na prova");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(33, 150, 243));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("+");
        jButton4.setToolTipText("Acresentar multipla escolha na prova");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(33, 150, 243));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("-");
        jButton5.setToolTipText("Subtrair verdadeiro ou falso na prova");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(33, 150, 243));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("+");
        jButton6.setToolTipText("Acresentar verdadeiro ou falso na prova");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temaGerar)
                    .addComponent(disciplinaGerar, 0, 975, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numDiserta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(numVF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(medianaGerar, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(facilGerar, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(dificilGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(155, 155, 155)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(nQuestoesGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(enviarGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disciplinaGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(temaGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facilGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(numDiserta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton3))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medianaGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(numME)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton5))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dificilGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(numVF)))
                .addGap(41, 41, 41)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nQuestoesGerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A ferramenta que produz provas de maneira simples e funcional");
        jLabel10.setToolTipText("Descrição");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarGerarActionPerformed
        ArrayList<String> erros = new ArrayList();
        ConexaoBD conn = new ConexaoBD();
        
        if(disciplinaGerar.getSelectedIndex() == 0) erros.add("Disciplina não definida");
        if(temaGerar.getText().trim().equals("DIGITE O TEXTO AQUI.")) erros.add("Não ha temas definidos");
        
         String errorList = "";
            for (String erro : erros) {
                errorList += erro + "\n";
            }
            if(!(errorList.isEmpty())) {
                JOptionPane.showMessageDialog(this, errorList, "ERRO",
                    JOptionPane.ERROR_MESSAGE);
            } else{
            
                if(numDiserta.getText().equals("?")){
                       ProvaGenerica provaGenerica = new ProvaGenerica();
                       provaGenerica.setMateria(disciplinaGerar.getSelectedItem().toString());
                       provaGenerica.setConteudos(new ArrayList(Arrays.asList(
                               temaGerar.getText().trim().replace(" ", "").split(","))));
                       provaGenerica.setIsFacil(facilGerar.isSelected());
                       provaGenerica.setIsMediana(medianaGerar.isSelected());
                       provaGenerica.setIsDificil(dificilGerar.isSelected());
                       provaGenerica.setNumQuestoes(nQuestoesGerar.getValue());

                    try {
                        provaGenerica.gerar();
                           EscreveXML escreveXML = new EscreveXML(provaGenerica.toXML());
                           
                        conn.enviarProvaDB(provaGenerica);
                    } catch (SQLException | SAXException | ParserConfigurationException | IOException ex) {
                       JOptionPane.showMessageDialog(this,"ERRO:" + ex.getMessage(), "ERRO",
                            JOptionPane.ERROR_MESSAGE);
                     
                    }

                   } else {
                       ProvaEspecifica provaEspecifica = new ProvaEspecifica();
                       provaEspecifica.setMateria(disciplinaGerar.getSelectedItem().toString());
                       provaEspecifica.setConteudos(new ArrayList(
                               Arrays.asList(temaGerar.getText().trim().replace(" ", "").split(","))));
                       provaEspecifica.setIsFacil(facilGerar.isSelected());
                       provaEspecifica.setIsMediana(medianaGerar.isSelected());
                       provaEspecifica.setIsDificil(dificilGerar.isSelected());
                       provaEspecifica.setNumMultiplaEscolha(Integer.parseInt(numME.getText()));
                       provaEspecifica.setNumVF(Integer.parseInt(numVF.getText()));
                       provaEspecifica.setNumAbertas(Integer.parseInt(numDiserta.getText()));
                       
                       
                     try {
                        provaEspecifica.gerar();
                        
                        EscreveXML escreveXML = new EscreveXML(provaEspecifica.toXML());
                        conn.enviarProvaDB(provaEspecifica);

                    } catch (SQLException | SAXException | ParserConfigurationException | IOException ex) {
                       JOptionPane.showMessageDialog(this,"ERRO:" + ex.getMessage(), "ERRO",
                            JOptionPane.ERROR_MESSAGE);
                    }
                   }
                JOptionPane.showMessageDialog(this, "Prova gerada com sucesso.", "SUCESSO",
                            JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new FormInicial().setVisible(true);
            }
    }//GEN-LAST:event_enviarGerarActionPerformed

    private void homeGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeGerarActionPerformed
        FormInicial home = new FormInicial();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeGerarActionPerformed

    private void nQuestoesGerarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nQuestoesGerarStateChanged
        // TODO add your handling code here:
        jLabel11.setText("Defina o número de questões: " 
                + nQuestoesGerar.getValue());
        nQuestoesGerar.setToolTipText(nQuestoesGerar.getValue() + " questões a serem adicionadas na prova");
    }//GEN-LAST:event_nQuestoesGerarStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(numDiserta.getText().equals("?")){
           numDiserta.setText("0");
           numVF.setText("0");
           numME.setText("0");
       } else{
          if(Integer.parseInt(numDiserta.getText().trim()) > -1 
                  && (Integer.parseInt(numDiserta.getText().trim()) + Integer.parseInt(numME.getText().trim()) 
                  + Integer.parseInt(numVF.getText().trim())) < 101)
              numDiserta.setText("" + (Integer.parseInt(numDiserta.getText().trim()) + 1));
           nQuestoesGerar.setValue(Integer.parseInt(numDiserta.getText().trim()) + 
                   Integer.parseInt(numME.getText().trim()) + Integer.parseInt(numVF.getText().trim()));
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(numDiserta.getText().equals("?")){
           numDiserta.setText("0");
           numVF.setText("0");
           numME.setText("0");
       } else{
          if(Integer.parseInt(numDiserta.getText().trim()) > 0 )  
              numDiserta.setText("" + (Integer.parseInt(numDiserta.getText().trim()) - 1));
           nQuestoesGerar.setValue(Integer.parseInt(numDiserta.getText().trim()) + 
                   Integer.parseInt(numME.getText().trim()) + Integer.parseInt(numVF.getText().trim()));
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(numDiserta.getText().equals("?")){
           numDiserta.setText("0");
           numVF.setText("0");
           numME.setText("0");
       } else{
          if(Integer.parseInt(numME.getText().trim()) > -1 && (Integer.parseInt(numDiserta.getText().trim()) 
                  + Integer.parseInt(numME.getText().trim()) 
                  + Integer.parseInt(numVF.getText().trim())) < 101)
              numME.setText("" + (Integer.parseInt(numME.getText().trim()) + 1));
           nQuestoesGerar.setValue(Integer.parseInt(numDiserta.getText().trim()) + 
                   Integer.parseInt(numME.getText().trim()) + Integer.parseInt(numVF.getText().trim()));
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(numDiserta.getText().equals("?")){
           numDiserta.setText("0");
           numVF.setText("0");
           numME.setText("0");
       } else{
          if(Integer.parseInt(numME.getText().trim()) > 0 )  
              numME.setText("" + (Integer.parseInt(numME.getText().trim()) - 1));
           nQuestoesGerar.setValue(Integer.parseInt(numDiserta.getText().trim()) + 
                   Integer.parseInt(numME.getText().trim()) + Integer.parseInt(numVF.getText().trim()));
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       if(numDiserta.getText().equals("?")){
           numDiserta.setText("0");
           numVF.setText("0");
           numME.setText("0");
       } else{
          if(Integer.parseInt(numVF.getText().trim()) > -1 && (Integer.parseInt(numDiserta.getText().trim()) 
                  + Integer.parseInt(numME.getText().trim()) 
                  + Integer.parseInt(numVF.getText().trim())) < 101) 
              numVF.setText("" + (Integer.parseInt(numVF.getText().trim()) + 1));
           nQuestoesGerar.setValue(Integer.parseInt(numDiserta.getText().trim()) + 
                   Integer.parseInt(numME.getText().trim()) + Integer.parseInt(numVF.getText().trim()));
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      if(numDiserta.getText().equals("?")){
           numDiserta.setText("0");
           numVF.setText("0");
           numME.setText("0");
       } else{
          if(Integer.parseInt(numVF.getText().trim()) > 0 )  
              numVF.setText("" + (Integer.parseInt(numVF.getText().trim()) - 1));
           nQuestoesGerar.setValue(Integer.parseInt(numDiserta.getText().trim()) + 
                   Integer.parseInt(numME.getText().trim()) + Integer.parseInt(numVF.getText().trim()));
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nQuestoesGerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nQuestoesGerarMouseClicked

    }//GEN-LAST:event_nQuestoesGerarMouseClicked

    private void nQuestoesGerarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nQuestoesGerarMousePressed
        numDiserta.setText("?");
         numVF.setText("?");
         numME.setText("?");
    }//GEN-LAST:event_nQuestoesGerarMousePressed

    private void temaGerarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temaGerarFocusGained
        if(temaGerar.getText().equals("DIGITE O TEXTO AQUI.")){
           temaGerar.setText("");
           temaGerar.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_temaGerarFocusGained

    private void temaGerarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temaGerarFocusLost
        if(temaGerar.getText().equals("")){
           temaGerar.setText("DIGITE O TEXTO AQUI.");
           temaGerar.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_temaGerarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Gerar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dificilGerar;
    private javax.swing.JComboBox<String> disciplinaGerar;
    private javax.swing.JButton enviarGerar;
    private javax.swing.JCheckBox facilGerar;
    private javax.swing.JButton homeGerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox medianaGerar;
    private javax.swing.JSlider nQuestoesGerar;
    private javax.swing.JLabel numDiserta;
    private javax.swing.JLabel numME;
    private javax.swing.JLabel numVF;
    private javax.swing.JTextField temaGerar;
    // End of variables declaration//GEN-END:variables
}
