/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import bancodequestoes.Alternativa;
import bancodequestoes.ConexaoBD;
import bancodequestoes.Imagem;
import bancodequestoes.MultiplaEscolha;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Paiva Morais
 */
public class InserirME extends javax.swing.JFrame {
    
      /** Define se esta é uma janela de edição ou de inserção */
    private boolean editar;
    /** Se a imagem for para ser editada pega o ID dela */
    private int idEditar;
    
    
    /**
     * Creates new form Inserir
     */
    public InserirME() {
        initComponents();
    }

        /**
     * Caso a janela sirva para editar a questão
     * @param multiplaEscolha O objeto da antiga questão
     * @param idEditar o id da questão editada
     */
    public  InserirME(MultiplaEscolha multiplaEscolha, int idEditar){
        initComponents();
        editar = true;
        this.idEditar = idEditar;
        
        this.disciplinaME.setSelectedItem(multiplaEscolha.getMateria());
        this.temaME.setText(multiplaEscolha.getConteudo());
        this.temaME.setForeground(new Color(0, 0, 0));
        this.dificuldadeME.setSelectedIndex(multiplaEscolha.getDificuldade());
        this.enunciadoME.setText(multiplaEscolha.getEnunciado());
        this.enunciadoME.setForeground(new Color(0,0,0));
        this.aleatorioCHK.setState(multiplaEscolha.isAleatoria());
        
    //Pega a alternativas   
        for (Alternativa alternativa : multiplaEscolha.getAlternativas()) {
            if(alternativa.IsCorreta()){
                this.gabaritoME.setText(alternativa.getTexto());
                this.gabaritoME.setForeground(new Color(0,0,0));
            } else {
                //Gambiarra só por que eu to desinteressado
                if(this.alternativa1.getText().equals("DIGITE O TEXTO AQUI.")){
                    this.alternativa1.setText(alternativa.getTexto());
                    this.alternativa1.setForeground(new Color(0,0,0));
                } else if(this.alternativa2.getText().equals("DIGITE O TEXTO AQUI.")){
                    this.alternativa2.setText(alternativa.getTexto());
                    this.alternativa2.setForeground(new Color(0,0,0));
                } else if(this.alternativa3.getText().equals("DIGITE O TEXTO AQUI.")){
                    this.alternativa3.setText(alternativa.getTexto());
                    this.alternativa3.setForeground(new Color(0,0,0));
                } else if(this.alternativa4.getText().equals("DIGITE O TEXTO AQUI.")){
                    this.alternativa4.setText(alternativa.getTexto());
                    this.alternativa4.setForeground(new Color(0,0,0));
                } 
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seletorArq = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        homeME = new javax.swing.JButton();
        disciplinaME = new javax.swing.JComboBox<>();
        temaME = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dificuldadeME = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        enviarME = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enunciadoME = new javax.swing.JTextField();
        respostaQuestao = new javax.swing.JLabel();
        gabaritoME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alternativa1 = new javax.swing.JTextField();
        alternativa2 = new javax.swing.JTextField();
        alternativa3 = new javax.swing.JTextField();
        alternativa4 = new javax.swing.JTextField();
        fileME = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelImagem = new javax.swing.JLabel();
        imagemBTN = new javax.swing.JButton();
        desfazerImagem = new javax.swing.JButton();
        aleatorioCHK = new java.awt.Checkbox();

        seletorArq.setFileSelectionMode(JFileChooser.FILES_ONLY);
        seletorArq.setFileFilter(new FileNameExtensionFilter("JPG Images", "jpg"));
        seletorArq.setAcceptAllFileFilterUsed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1028, 850));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 87, 155));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Banco de Questões");
        jLabel7.setToolTipText("Banco de Questões");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setAlignmentX(0.5F);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        homeME.setBackground(new java.awt.Color(33, 150, 243));
        homeME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        homeME.setForeground(new java.awt.Color(255, 255, 255));
        homeME.setText("HOME");
        homeME.setToolTipText("Ir pára o inicio");
        homeME.setAlignmentX(0.5F);
        homeME.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMEActionPerformed(evt);
            }
        });

        disciplinaME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        disciplinaME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina a disciplina:", "Aplicações para Web", "Arquitetura de Sistemas Digitais", "Linguagem de Programação - JAVA", "Manutenção de Computadores", "Biologia", "Filosofia", "Física", "Geografia", "História", "Matemática", "Português", "Química", "Sociologia", "Outra" }));
        disciplinaME.setToolTipText("Defina a disciplina");

        temaME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        temaME.setForeground(new java.awt.Color(153, 153, 153));
        temaME.setText("DIGITE O TEXTO AQUI.");
        temaME.setToolTipText("Defina o tema");
        temaME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                temaMEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temaMEFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Digite o tema:");
        jLabel9.setToolTipText("Defina o tema");

        dificuldadeME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dificuldadeME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina o nível de dificuldade da questão:", "Fácil", "Mediana", "Díficil" }));
        dificuldadeME.setToolTipText("Defina a dificuldade");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeME, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temaME)
                    .addComponent(disciplinaME, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dificuldadeME, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeME, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disciplinaME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temaME, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificuldadeME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A ferramenta que produz provas de maneira simples e funcional");
        jLabel10.setToolTipText("Descrição");

        enviarME.setBackground(new java.awt.Color(33, 150, 243));
        enviarME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enviarME.setForeground(new java.awt.Color(255, 255, 255));
        enviarME.setText("ENVIAR");
        enviarME.setToolTipText("Enviar para o banco de dados");
        enviarME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Digite o enunciado da questão:");
        jLabel1.setToolTipText("Defina o enunciado da questão");

        enunciadoME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enunciadoME.setForeground(new java.awt.Color(153, 153, 153));
        enunciadoME.setText("DIGITE O TEXTO AQUI.");
        enunciadoME.setToolTipText("Defina o enunciado da questão");
        enunciadoME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enunciadoMEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enunciadoMEFocusLost(evt);
            }
        });

        respostaQuestao.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        respostaQuestao.setForeground(new java.awt.Color(153, 153, 153));
        respostaQuestao.setText("Digite a alternativa correta da questão:");
        respostaQuestao.setToolTipText("Defina a alternativa correta");

        gabaritoME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        gabaritoME.setForeground(new java.awt.Color(153, 153, 153));
        gabaritoME.setText("DIGITE O TEXTO AQUI.");
        gabaritoME.setToolTipText("Defina a alternativa correta");
        gabaritoME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gabaritoMEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gabaritoMEFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Digite as alternativas incorretas:");
        jLabel3.setToolTipText("Defina a alternativa incorreta");

        alternativa1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alternativa1.setForeground(new java.awt.Color(153, 153, 153));
        alternativa1.setText("DIGITE O TEXTO AQUI.");
        alternativa1.setToolTipText("Defina uma alternativa qualquer");
        alternativa1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alternativa1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alternativa1FocusLost(evt);
            }
        });
        alternativa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa1ActionPerformed(evt);
            }
        });

        alternativa2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alternativa2.setForeground(new java.awt.Color(153, 153, 153));
        alternativa2.setText("DIGITE O TEXTO AQUI.");
        alternativa2.setToolTipText("Defina uma alternativa qualquer");
        alternativa2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alternativa2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alternativa2FocusLost(evt);
            }
        });

        alternativa3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alternativa3.setForeground(new java.awt.Color(153, 153, 153));
        alternativa3.setText("DIGITE O TEXTO AQUI.");
        alternativa3.setToolTipText("Defina uma alternativa qualquer");
        alternativa3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alternativa3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alternativa3FocusLost(evt);
            }
        });
        alternativa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa3ActionPerformed(evt);
            }
        });

        alternativa4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alternativa4.setForeground(new java.awt.Color(153, 153, 153));
        alternativa4.setText("DIGITE O TEXTO AQUI.");
        alternativa4.setToolTipText("Defina uma alternativa qualquer");
        alternativa4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alternativa4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alternativa4FocusLost(evt);
            }
        });

        fileME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Selecione uma imagem para a questão(opcional):");
        jLabel4.setToolTipText("Defina uma imagem para a questão");

        labelImagem.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        labelImagem.setForeground(new java.awt.Color(153, 153, 153));
        labelImagem.setText("CAMINHO DA IMAGEM:");
        labelImagem.setToolTipText("O caminho da imagem no seu computador");

        imagemBTN.setBackground(new java.awt.Color(33, 150, 243));
        imagemBTN.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        imagemBTN.setForeground(new java.awt.Color(255, 255, 255));
        imagemBTN.setText("SELECIONAR IMAGEM");
        imagemBTN.setToolTipText("Selecionar imagem");
        imagemBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemBTNActionPerformed(evt);
            }
        });

        desfazerImagem.setBackground(new java.awt.Color(153, 153, 153));
        desfazerImagem.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        desfazerImagem.setForeground(new java.awt.Color(255, 255, 255));
        desfazerImagem.setText("DESFAZER");
        desfazerImagem.setEnabled(false);
        desfazerImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desfazerImagemActionPerformed(evt);
            }
        });

        aleatorioCHK.setLabel("Alternativas Aleatorias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(enunciadoME)
                                .addComponent(respostaQuestao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gabaritoME, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alternativa2)
                                .addComponent(alternativa1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(aleatorioCHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(enviarME, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(imagemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(desfazerImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(fileME, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(alternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alternativa3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aleatorioCHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciadoME, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respostaQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gabaritoME, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fileME, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(imagemBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(desfazerImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarME, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMEActionPerformed
        FormInicial home = new FormInicial();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMEActionPerformed

    private void enviarMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMEActionPerformed
        ConexaoBD conn = new ConexaoBD(); 
        ArrayList<String> erros = new ArrayList();
        ArrayList<Alternativa> alternativas = new ArrayList(5);
        MultiplaEscolha multiplaEscolha = new MultiplaEscolha();
        
        if(disciplinaME.getSelectedIndex() == 0) erros.add("Disciplina não definida");
        if(temaME.getText().trim().equals("")) erros.add("Não ha temas definidos");
        if(dificuldadeME.getSelectedIndex() == 0) erros.add("Não ha dificuldade selecionada.");
        if(enunciadoME.getText().trim().equals("")) erros.add("Não ha enunciado definido");
        //Alternativas
        if(!(gabaritoME.getText().trim().isEmpty())
                && !(alternativa1.getText().trim().isEmpty())){
           alternativas.add(new Alternativa(gabaritoME.getText().trim(),true));
           alternativas.add(new Alternativa(alternativa1.getText().trim(),false));
           
           if(!(alternativa2.getText().trim().isEmpty())){
               alternativas.add(new Alternativa(alternativa2.getText().trim(),false));
           }
           
           if(!(alternativa3.getText().trim().isEmpty())){
               alternativas.add(new Alternativa(alternativa3.getText().trim(),false));
           }
           
           if(!(alternativa4.getText().trim().isEmpty())){
               alternativas.add(new Alternativa(alternativa4.getText().trim(),false));
           }
           
        } else erros.add("Não ha alternativas suficientes definidas.");
        
        if(erros.isEmpty()){
            multiplaEscolha.setMateria(disciplinaME.getSelectedItem().toString());
            multiplaEscolha.setConteudo(temaME.getText().trim().replace(" ", ""));
            multiplaEscolha.setDificuldade((byte) dificuldadeME.getSelectedIndex());
            multiplaEscolha.setEnunciado(enunciadoME.getText().trim());
            multiplaEscolha.setAlternativas(alternativas);
            multiplaEscolha.setAleatoria(aleatorioCHK.getState());
            
            if(!(labelImagem.getText().equals("CAMINHO DA IMAGEM:"))){
                multiplaEscolha.setImagem(new Imagem(labelImagem.getText()));
            }
            
            try {
                if(editar){ //se for pra editar questão caso contrario insere
                    conn.editQuestaobd(idEditar, multiplaEscolha);
                    JOptionPane.showMessageDialog(this, "Questão editada com sucesso"
                   + " no banco.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                    
                } else{ 
                    conn.addQuestaobd(multiplaEscolha);
                
                JOptionPane.showMessageDialog(this, "Questão adicionada com sucesso"
                        + " no banco.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de "
                            + "dados. Cheque sua conexão.", "ERRO",
                            JOptionPane.ERROR_MESSAGE);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "ERRO Ocorreu algum "
                            + "erro de input.", "ERRO",
                            JOptionPane.ERROR_MESSAGE);
                }
                    this.setVisible(false);
            new FormInicial().setVisible(true);
        } else{
            String errorList = "";
            for (String erro : erros) {
                errorList += erro + "\n";
            }
            JOptionPane.showMessageDialog(this, errorList, "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_enviarMEActionPerformed

    private void imagemBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemBTNActionPerformed
         if(seletorArq.showOpenDialog(jPanel1) == 1){
            JOptionPane.showMessageDialog(jPanel1, "Não foi selecionado nenum arquivo valido.");
        }else{
            labelImagem.setText(seletorArq.getSelectedFile().getAbsolutePath());
            
            desfazerImagem.setBackground(new Color(33,150,243));
            desfazerImagem.setEnabled(true);
        }
    }//GEN-LAST:event_imagemBTNActionPerformed

    private void desfazerImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desfazerImagemActionPerformed
       desfazerImagem.setBackground(new Color(153,153,153));
          desfazerImagem.setEnabled(false);
        
        labelImagem.setText("CAMINHO DA IMAGEM:");       
    }//GEN-LAST:event_desfazerImagemActionPerformed

    private void alternativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa1ActionPerformed

    private void enunciadoMEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enunciadoMEFocusGained
        if(enunciadoME.getText().equals("DIGITE O TEXTO AQUI.")){
           enunciadoME.setText("");
           enunciadoME.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_enunciadoMEFocusGained

    private void gabaritoMEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gabaritoMEFocusGained
        if(gabaritoME.getText().equals("DIGITE O TEXTO AQUI.")){
           gabaritoME.setText("");
           gabaritoME.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_gabaritoMEFocusGained

    private void alternativa1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alternativa1FocusGained
        if(alternativa1.getText().equals("DIGITE O TEXTO AQUI.")){
           alternativa1.setText("");
           alternativa1.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alternativa1FocusGained

    private void alternativa2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alternativa2FocusGained
        if(alternativa2.getText().equals("DIGITE O TEXTO AQUI.")){
           alternativa2.setText("");
           alternativa2.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alternativa2FocusGained

    private void alternativa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa3ActionPerformed

    private void alternativa3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alternativa3FocusGained
        if(alternativa3.getText().equals("DIGITE O TEXTO AQUI.")){
           alternativa3.setText("");
           alternativa3.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alternativa3FocusGained

    private void alternativa4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alternativa4FocusGained
        if(alternativa4.getText().equals("DIGITE O TEXTO AQUI.")){
           alternativa4.setText("");
           alternativa4.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alternativa4FocusGained

    private void alternativa4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alternativa4FocusLost
       if(alternativa4.getText().equals("")){
            alternativa4.setText("DIGITE O TEXTO AQUI.");
            alternativa4.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alternativa4FocusLost

    private void alternativa3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alternativa3FocusLost
       if(alternativa3.getText().equals("")){
            alternativa3.setText("DIGITE O TEXTO AQUI.");
            alternativa3.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alternativa3FocusLost

    private void alternativa2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alternativa2FocusLost
       if(alternativa2.getText().equals("")){
            alternativa2.setText("DIGITE O TEXTO AQUI.");
            alternativa2.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alternativa2FocusLost

    private void alternativa1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alternativa1FocusLost
       if(alternativa1.getText().equals("")){
            alternativa1.setText("DIGITE O TEXTO AQUI.");
            alternativa1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alternativa1FocusLost

    private void gabaritoMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gabaritoMEFocusLost
        if(gabaritoME.getText().equals("")){
            gabaritoME.setText("DIGITE O TEXTO AQUI.");
            gabaritoME.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_gabaritoMEFocusLost

    private void enunciadoMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enunciadoMEFocusLost
        if(enunciadoME.getText().equals("")){
            enunciadoME.setText("DIGITE O TEXTO AQUI.");
            enunciadoME.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_enunciadoMEFocusLost

    private void temaMEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temaMEFocusGained
        if(temaME.getText().equals("DIGITE O TEXTO AQUI.")){
           temaME.setText("");
           temaME.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_temaMEFocusGained

    private void temaMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temaMEFocusLost
        if(temaME.getText().equals("")){
            temaME.setText("DIGITE O TEXTO AQUI.");
            temaME.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_temaMEFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InserirME().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox aleatorioCHK;
    private javax.swing.JTextField alternativa1;
    private javax.swing.JTextField alternativa2;
    private javax.swing.JTextField alternativa3;
    private javax.swing.JTextField alternativa4;
    private javax.swing.JButton desfazerImagem;
    private javax.swing.JComboBox<String> dificuldadeME;
    private javax.swing.JComboBox<String> disciplinaME;
    private javax.swing.JTextField enunciadoME;
    private javax.swing.JButton enviarME;
    private javax.swing.JLabel fileME;
    private javax.swing.JTextField gabaritoME;
    private javax.swing.JButton homeME;
    private javax.swing.JButton imagemBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel respostaQuestao;
    private javax.swing.JFileChooser seletorArq;
    private javax.swing.JTextField temaME;
    // End of variables declaration//GEN-END:variables
}
