/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import bancodequestoes.Aberta;
import bancodequestoes.ConexaoBD;
import bancodequestoes.Imagem;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Paiva Morais
 */
public class InserirAberta extends javax.swing.JFrame {
    /** Define se esta é uma janela de edição ou de inserção */
    private boolean editar;
    /** Se a imagem for para ser editada pega o ID dela */
    private int idEditar;
    
    /**
     * Creates new form Inserir
     */
    public InserirAberta() {
        initComponents();
    }
    
    /**
     * Caso a janela sirva para editar a questão
     * @param aberta O objeto da antiga questão
     * @param idEditar o id da questão editada
     */
    public  InserirAberta(Aberta aberta, int idEditar){
        initComponents();
        editar = true;
        this.idEditar = idEditar;
        
        this.disciplinaAberta.setSelectedItem(aberta.getMateria());
        this.temaAberta.setText(aberta.getConteudo());
        this.temaAberta.setForeground(new Color(0,0,0));
        this.dificuldadeAberta.setSelectedIndex(aberta.getDificuldade());
        this.enunciadoAberta.setText(aberta.getEnunciado());
        this.enunciadoAberta.setForeground(new Color(0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seletorArq = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        homeAberta = new javax.swing.JButton();
        disciplinaAberta = new javax.swing.JComboBox<>();
        temaAberta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dificuldadeAberta = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        enviarAberta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enunciadoAberta = new javax.swing.JTextField();
        imagemBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelImagem = new javax.swing.JLabel();
        imagemAberta2 = new javax.swing.JButton();
        desfazerImagem = new javax.swing.JButton();

        seletorArq.setFileSelectionMode(JFileChooser.FILES_ONLY);
        seletorArq.setFileFilter(new FileNameExtensionFilter("JPG Images", "jpg"));
        seletorArq.setAcceptAllFileFilterUsed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1028, 700));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 87, 155));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Banco de Questões");
        jLabel7.setToolTipText("Banco de Questões");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setAlignmentX(0.5F);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        homeAberta.setBackground(new java.awt.Color(33, 150, 243));
        homeAberta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        homeAberta.setForeground(new java.awt.Color(255, 255, 255));
        homeAberta.setText("HOME");
        homeAberta.setToolTipText("Ir para o inicio");
        homeAberta.setAlignmentX(0.5F);
        homeAberta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeAberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAbertaActionPerformed(evt);
            }
        });

        disciplinaAberta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        disciplinaAberta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina a disciplina:", "Aplicações para Web", "Arquitetura de Sistemas Digitais", "Linguagem de Programação - JAVA", "Manutenção de Computadores", "Biologia", "Filosofia", "Física", "Geografia", "História", "Matemática", "Português", "Química", "Sociologia", "Outra" }));
        disciplinaAberta.setToolTipText("Defina a discioplina");

        temaAberta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        temaAberta.setForeground(new java.awt.Color(153, 153, 153));
        temaAberta.setText("DIGITE O TEXTO AQUI.");
        temaAberta.setToolTipText("Defina o tema");
        temaAberta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                temaAbertaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temaAbertaFocusLost(evt);
            }
        });
        temaAberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaAbertaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Digite o tema:");
        jLabel9.setToolTipText("Defina o tema");

        dificuldadeAberta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dificuldadeAberta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina o nível de dificuldade da questão:", "Fácil", "Mediana", "Díficil" }));
        dificuldadeAberta.setToolTipText("Defina a dificuldade da questão");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temaAberta)
                    .addComponent(disciplinaAberta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dificuldadeAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(disciplinaAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temaAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificuldadeAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A ferramenta que produz provas de maneira simples e funcional");
        jLabel10.setToolTipText("Descrição");

        enviarAberta.setBackground(new java.awt.Color(33, 150, 243));
        enviarAberta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enviarAberta.setForeground(new java.awt.Color(255, 255, 255));
        enviarAberta.setText("ENVIAR");
        enviarAberta.setToolTipText("Enviar para o banco de dados");
        enviarAberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAbertaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Digite o enunciado da questão:");
        jLabel1.setToolTipText("Defina o enunciado");

        enunciadoAberta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enunciadoAberta.setForeground(new java.awt.Color(153, 153, 153));
        enunciadoAberta.setText("DIGITE O TEXTO AQUI.");
        enunciadoAberta.setToolTipText("Defina o enunciado");
        enunciadoAberta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enunciadoAbertaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enunciadoAbertaFocusLost(evt);
            }
        });
        enunciadoAberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enunciadoAbertaActionPerformed(evt);
            }
        });

        imagemBTN.setBackground(new java.awt.Color(33, 150, 243));
        imagemBTN.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        imagemBTN.setForeground(new java.awt.Color(255, 255, 255));
        imagemBTN.setText("SELECIONAR IMAGEM");
        imagemBTN.setToolTipText("Selecionar imagem do seu computador");
        imagemBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemBTNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Selecione uma imagem para a questão(opcional):");
        jLabel3.setToolTipText("Imagem da questão");

        labelImagem.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        labelImagem.setForeground(new java.awt.Color(153, 153, 153));
        labelImagem.setText("CAMINHO DA IMAGEM:");
        labelImagem.setToolTipText("Caminho da imagem da questão");

        imagemAberta2.setBackground(new java.awt.Color(33, 150, 243));
        imagemAberta2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        imagemAberta2.setForeground(new java.awt.Color(255, 255, 255));
        imagemAberta2.setText("SELECIONAR IMAGEM");
        imagemAberta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemAberta2ActionPerformed(evt);
            }
        });

        desfazerImagem.setBackground(new java.awt.Color(153, 153, 153));
        desfazerImagem.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        desfazerImagem.setForeground(new java.awt.Color(255, 255, 255));
        desfazerImagem.setText("DESFAZER");
        desfazerImagem.setEnabled(false);
        desfazerImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desfazerImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1075, 1075, 1075))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(1884, 1884, 1884))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(enviarAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imagemAberta2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(imagemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(desfazerImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(enunciadoAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enunciadoAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desfazerImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelImagem)
                        .addComponent(imagemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagemAberta2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enviarAberta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane2.setViewportView(jPanel1);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagemBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemBTNActionPerformed
        if(seletorArq.showOpenDialog(jPanel1) == 1){
            JOptionPane.showMessageDialog(jPanel1, "Não foi selecionado nenum arquivo valido.");
        }else{
            labelImagem.setText(seletorArq.getSelectedFile().getAbsolutePath());
            
            desfazerImagem.setBackground(new Color(33,150,243));
            desfazerImagem.setEnabled(true);
        }
    }//GEN-LAST:event_imagemBTNActionPerformed

    private void enviarAbertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarAbertaActionPerformed
        ConexaoBD conn = new ConexaoBD();
        ArrayList<String> erros = new ArrayList();
        Aberta aberta = new Aberta();

        if(disciplinaAberta.getSelectedIndex() == 0) erros.add("Disciplina não definida");
        if(temaAberta.getText().trim().equals("")) erros.add("Não ha temas definidos");
        if(dificuldadeAberta.getSelectedIndex() == 0) erros.add("Não ha dificuldade selecionada.");
        if(enunciadoAberta.getText().trim().equals("")) erros.add("Não ha enunciado definido");
        
        
        if(erros.isEmpty()){
            aberta.setMateria(disciplinaAberta.getSelectedItem().toString());
            aberta.setConteudo(temaAberta.getText().trim().replace(" ", ""));
            aberta.setDificuldade((byte) dificuldadeAberta.getSelectedIndex());
            aberta.setEnunciado(enunciadoAberta.getText().trim());
            
            if(!(labelImagem.getText().equals("CAMINHO DA IMAGEM:"))){
                aberta.setImagem(new Imagem(labelImagem.getText()));
            }

            try {
                if(editar){ //se for pra editar questão caso contrario insere
                    conn.editQuestaobd(idEditar, aberta);
                    JOptionPane.showMessageDialog(this, "Questão editada com sucesso"
                   + " no banco.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                } else { 
                    conn.addQuestaobd(aberta);
               JOptionPane.showMessageDialog(this, "Questão adicionada com sucesso"
                   + " no banco.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de "
                   + "dados. Cheque sua conexão."  , "ERRO",
                   JOptionPane.ERROR_MESSAGE);
              
           } catch (IOException ex) {
               JOptionPane.showMessageDialog(this, "ERRO Ocorreu algum "
                   + "erro de input.", "ERRO",
                   JOptionPane.ERROR_MESSAGE);
           }
            
             this.setVisible(false);
            new FormInicial().setVisible(true);
        } else{
            String errorList = "";
            for (String erro : erros) {
                errorList += erro + "\n";
            }
            JOptionPane.showMessageDialog(this, errorList, "ERRO",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enviarAbertaActionPerformed

    private void homeAbertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAbertaActionPerformed
        FormInicial home = new FormInicial();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeAbertaActionPerformed

    private void imagemAberta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemAberta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagemAberta2ActionPerformed

    private void desfazerImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desfazerImagemActionPerformed
          desfazerImagem.setBackground(new Color(153,153,153));
          desfazerImagem.setEnabled(false);
        
        labelImagem.setText("CAMINHO DA IMAGEM:");       
    }//GEN-LAST:event_desfazerImagemActionPerformed

    private void enunciadoAbertaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enunciadoAbertaFocusGained
       if(enunciadoAberta.getText().equals("DIGITE O TEXTO AQUI.")){
           enunciadoAberta.setText("");
           enunciadoAberta.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_enunciadoAbertaFocusGained

    private void enunciadoAbertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enunciadoAbertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enunciadoAbertaActionPerformed

    private void enunciadoAbertaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enunciadoAbertaFocusLost
        if(enunciadoAberta.getText().equals("")){
            enunciadoAberta.setText("DIGITE O TEXTO AQUI.");
            enunciadoAberta.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_enunciadoAbertaFocusLost

    private void temaAbertaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temaAbertaFocusGained
        if(temaAberta.getText().equals("DIGITE O TEXTO AQUI.")){
           temaAberta.setText("");
           temaAberta.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_temaAbertaFocusGained

    private void temaAbertaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temaAbertaFocusLost
        if(temaAberta.getText().equals("")){
            temaAberta.setText("DIGITE O TEXTO AQUI.");
            temaAberta.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_temaAbertaFocusLost

    private void temaAbertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaAbertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temaAbertaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirAberta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirAberta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirAberta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirAberta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InserirAberta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton desfazerImagem;
    private javax.swing.JComboBox<String> dificuldadeAberta;
    private javax.swing.JComboBox<String> disciplinaAberta;
    private javax.swing.JTextField enunciadoAberta;
    private javax.swing.JButton enviarAberta;
    private javax.swing.JButton homeAberta;
    private javax.swing.JButton imagemAberta2;
    private javax.swing.JButton imagemBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JFileChooser seletorArq;
    private javax.swing.JTextField temaAberta;
    // End of variables declaration//GEN-END:variables
}
