/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import bancodequestoes.Alternativa;
import bancodequestoes.ConexaoBD;
import bancodequestoes.Imagem;
import bancodequestoes.VOuF;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Paiva Morais
 */
public class InserirVouF extends javax.swing.JFrame {

    /** Define se esta é uma janela de edição ou de inserção */
    private boolean editar;
    /** Se a imagem for para ser editada pega o ID dela */
    private int idEditar;
    
    /**
     * Creates new form Inserir
     */
    public InserirVouF() {
        initComponents();
    }

         /**
     * Caso a janela sirva para editar a questão
     * @param VouF O objeto da antiga questão
     * @param idEditar o id da questão editada
     */
    public  InserirVouF(VOuF VouF, int idEditar){
        initComponents();
        editar = true;
        this.idEditar = idEditar;
        
        this.disciplinaVouF.setSelectedItem(VouF.getMateria());
        this.temaVouF.setText(VouF.getMateria());
        this.temaVouF.setForeground(new Color(0,0,0));
        this.dificuldadeVouF.setSelectedIndex(VouF.getDificuldade());
        this.enunciadoVouF.setText(VouF.getEnunciado());
        this.enunciadoVouF.setForeground(new Color(0,0,0));
        this.aleatorioCHK.setState(VouF.isAleatoria());
        //Esse é um daqueles codigos que vou ficar com vegonha dps mas..
    //Pega a alternativas   
        for (Alternativa alternativa : VouF.getAlternativas()) {
            if(this.alt1vouf.getText().equals("DIGITE O TEXTO AQUI.")){
                this.alt1vouf.setText(alternativa.getTexto());
                this.alt1vouf.setForeground(new Color(0,0,0));
                if(alternativa.IsCorreta()){
                    this.alt1verdadeiro.setSelected(true);
                } else this.alt1verdadeiro.setSelected(false);
            } else if(this.alt2vouf.getText().equals("DIGITE O TEXTO AQUI.")){
                this.alt2vouf.setText(alternativa.getTexto());
                this.alt2vouf.setForeground(new Color(0,0,0));
                if(alternativa.IsCorreta()){
                    this.alt2verdadeiro.setSelected(true);
                } else this.alt2verdadeiro.setSelected(false);
            } else if(this.alt3vouf.getText().equals("DIGITE O TEXTO AQUI.")){
                this.alt3vouf.setText(alternativa.getTexto());
                this.alt3vouf.setForeground(new Color(0,0,0));
                if(alternativa.IsCorreta()){
                    this.alt3verdadeiro.setSelected(true);
                } else this.alt3verdadeiro.setSelected(false);
            } else if(this.alt4vouf.getText().equals("DIGITE O TEXTO AQUI.")){
                this.alt4vouf.setText(alternativa.getTexto());
                this.alt4vouf.setForeground(new Color(0,0,0));
                if(alternativa.IsCorreta()){
                    this.alt4verdadeiro.setSelected(true);
                } else this.alt4verdadeiro.setSelected(false);
            } else if(this.alt5vouf.getText().equals("DIGITE O TEXTO AQUI.")){
                this.alt5vouf.setText(alternativa.getTexto());
                this.alt5vouf.setForeground(new Color(0,0,0));
                if(alternativa.IsCorreta()){
                    this.alt5verdadeiro.setSelected(true);
                } else this.alt5verdadeiro.setSelected(false);
            } else if(this.alt6vouf.getText().equals("DIGITE O TEXTO AQUI.")){
                this.alt6vouf.setText(alternativa.getTexto());
                this.alt6vouf.setForeground(new Color(0,0,0));
                if(alternativa.IsCorreta()){
                    this.alt6verdadeiro.setSelected(true);
                } else this.alt6verdadeiro.setSelected(false);
            } else if(this.alt7vouf.getText().equals("DIGITE O TEXTO AQUI.")){
                this.alt7vouf.setText(alternativa.getTexto());
                this.alt7vouf.setForeground(new Color(0,0,0));
                if(alternativa.IsCorreta()){
                    this.alt7verdadeiro.setSelected(true);
                } else this.alt7verdadeiro.setSelected(false);
            } 
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seletorArq = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        homeVouF = new javax.swing.JButton();
        disciplinaVouF = new javax.swing.JComboBox<>();
        temaVouF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dificuldadeVouF = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        enviarVouF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enunciadoVouF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alt1vouf = new javax.swing.JTextField();
        alt2vouf = new javax.swing.JTextField();
        alt3vouf = new javax.swing.JTextField();
        alt4vouf = new javax.swing.JTextField();
        alt5vouf = new javax.swing.JTextField();
        alt6vouf = new javax.swing.JTextField();
        alt7vouf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alt1verdadeiro = new javax.swing.JRadioButton();
        alt1falso = new javax.swing.JRadioButton();
        alt2verdadeiro = new javax.swing.JRadioButton();
        alt2falso = new javax.swing.JRadioButton();
        alt3verdadeiro = new javax.swing.JRadioButton();
        alt3falso = new javax.swing.JRadioButton();
        alt4verdadeiro = new javax.swing.JRadioButton();
        alt5verdadeiro = new javax.swing.JRadioButton();
        alt6verdadeiro = new javax.swing.JRadioButton();
        alt4falso = new javax.swing.JRadioButton();
        alt5falso = new javax.swing.JRadioButton();
        alt6falso = new javax.swing.JRadioButton();
        alt7falso = new javax.swing.JRadioButton();
        alt7verdadeiro = new javax.swing.JRadioButton();
        labelImagem = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imagemBTN = new javax.swing.JButton();
        desfazerImagem = new javax.swing.JButton();
        aleatorioCHK = new java.awt.Checkbox();

        seletorArq.setFileSelectionMode(JFileChooser.FILES_ONLY);
        seletorArq.setFileFilter(new FileNameExtensionFilter("JPG Images", "jpg"));
        seletorArq.setAcceptAllFileFilterUsed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1028, 516));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1028, 865));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 87, 155));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Banco de Questões");
        jLabel7.setToolTipText("Banco de Questões");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setAlignmentX(0.5F);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        homeVouF.setBackground(new java.awt.Color(33, 150, 243));
        homeVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        homeVouF.setForeground(new java.awt.Color(255, 255, 255));
        homeVouF.setText("HOME");
        homeVouF.setToolTipText("Ir para o inicio");
        homeVouF.setAlignmentX(0.5F);
        homeVouF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeVouF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeVouFActionPerformed(evt);
            }
        });

        disciplinaVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        disciplinaVouF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina a disciplina:", "Aplicações para Web", "Arquitetura de Sistemas Digitais", "Linguagem de Programação - JAVA", "Manutenção de Computadores", "Biologia", "Filosofia", "Física", "Geografia", "História", "Matemática", "Português", "Química", "Sociologia", "Outra" }));
        disciplinaVouF.setToolTipText("Defina a disciplina da questão");

        temaVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        temaVouF.setForeground(new java.awt.Color(153, 153, 153));
        temaVouF.setText("DIGITE O TEXTO AQUI.");
        temaVouF.setToolTipText("Defina o tema");
        temaVouF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                temaVouFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temaVouFFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Digite o tema:");
        jLabel9.setToolTipText("Defina o tema");

        dificuldadeVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dificuldadeVouF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina o nível de dificuldade da questão:", "Fácil", "Mediana", "Díficil" }));
        dificuldadeVouF.setToolTipText("Defina a dificuldade");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temaVouF)
                    .addComponent(disciplinaVouF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dificuldadeVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disciplinaVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temaVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificuldadeVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A ferramenta que produz provas de maneira simples e funcional");
        jLabel10.setToolTipText("Descrição");

        enviarVouF.setBackground(new java.awt.Color(33, 150, 243));
        enviarVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enviarVouF.setForeground(new java.awt.Color(255, 255, 255));
        enviarVouF.setText("ENVIAR");
        enviarVouF.setToolTipText("Enviar Imagem pro BD");
        enviarVouF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarVouFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Digite o enunciado da questão:");
        jLabel1.setToolTipText("Defina o enunciado");

        enunciadoVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enunciadoVouF.setForeground(new java.awt.Color(153, 153, 153));
        enunciadoVouF.setText("DIGITE O TEXTO AQUI.");
        enunciadoVouF.setToolTipText("Defina o enunciado");
        enunciadoVouF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enunciadoVouFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enunciadoVouFFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Digite as alternativas:");
        jLabel3.setToolTipText("defina as alternativas");

        alt1vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt1vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt1vouf.setText("DIGITE O TEXTO AQUI.");
        alt1vouf.setToolTipText("Defina uma alternativa");
        alt1vouf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alt1voufFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alt1voufFocusLost(evt);
            }
        });

        alt2vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt2vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt2vouf.setText("DIGITE O TEXTO AQUI.");
        alt2vouf.setToolTipText("Defina uma alternativa");
        alt2vouf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alt2voufFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alt2voufFocusLost(evt);
            }
        });

        alt3vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt3vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt3vouf.setText("DIGITE O TEXTO AQUI.");
        alt3vouf.setToolTipText("Defina uma alternativa");
        alt3vouf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alt3voufFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alt3voufFocusLost(evt);
            }
        });

        alt4vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt4vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt4vouf.setText("DIGITE O TEXTO AQUI.");
        alt4vouf.setToolTipText("Defina uma alternativa");
        alt4vouf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alt4voufFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alt4voufFocusLost(evt);
            }
        });

        alt5vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt5vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt5vouf.setText("DIGITE O TEXTO AQUI.");
        alt5vouf.setToolTipText("Defina uma alternativa");
        alt5vouf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alt5voufFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alt5voufFocusLost(evt);
            }
        });

        alt6vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt6vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt6vouf.setText("DIGITE O TEXTO AQUI.");
        alt6vouf.setToolTipText("");
        alt6vouf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alt6voufFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alt6voufFocusLost(evt);
            }
        });

        alt7vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt7vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt7vouf.setText("DIGITE O TEXTO AQUI.");
        alt7vouf.setToolTipText("Defina uma alternativa");
        alt7vouf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alt7voufFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alt7voufFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Verdadeiro");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("Falso");

        alt1verdadeiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(alt1verdadeiro);
        alt1verdadeiro.setToolTipText("Defina se ela é verdadeira");

        alt1falso.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(alt1falso);
        alt1falso.setSelected(true);
        alt1falso.setToolTipText("Defina se ela é falsa");

        alt2verdadeiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(alt2verdadeiro);
        alt2verdadeiro.setToolTipText("Defina se ela é verdadeira");

        alt2falso.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(alt2falso);
        alt2falso.setSelected(true);
        alt2falso.setToolTipText("Defina se ela é falsa");

        alt3verdadeiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(alt3verdadeiro);
        alt3verdadeiro.setToolTipText("Defina se ela é verdadeira");

        alt3falso.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(alt3falso);
        alt3falso.setSelected(true);
        alt3falso.setToolTipText("Defina se ela é falsa");

        alt4verdadeiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(alt4verdadeiro);
        alt4verdadeiro.setToolTipText("Defina se ela é verdadeira");

        alt5verdadeiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(alt5verdadeiro);
        alt5verdadeiro.setToolTipText("Defina se ela é verdadeira");

        alt6verdadeiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(alt6verdadeiro);
        alt6verdadeiro.setToolTipText("Defina se ela é verdadeira");

        alt4falso.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(alt4falso);
        alt4falso.setSelected(true);
        alt4falso.setToolTipText("Defina se ela é falsa");

        alt5falso.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(alt5falso);
        alt5falso.setSelected(true);
        alt5falso.setToolTipText("Defina se ela é falsa");

        alt6falso.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(alt6falso);
        alt6falso.setSelected(true);
        alt6falso.setToolTipText("Defina se ela é falsa");

        alt7falso.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(alt7falso);
        alt7falso.setSelected(true);
        alt7falso.setToolTipText("Defina se ela é falsa");

        alt7verdadeiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(alt7verdadeiro);
        alt7verdadeiro.setToolTipText("Defina se ela é verdadeira");

        labelImagem.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        labelImagem.setForeground(new java.awt.Color(153, 153, 153));
        labelImagem.setText("CAMINHO DA IMAGEM:");
        labelImagem.setToolTipText("O caminho da imagem no seu computador");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Selecione uma imagem para a questão(opcional):");
        jLabel6.setToolTipText("Defina a imagem da questão");

        imagemBTN.setBackground(new java.awt.Color(33, 150, 243));
        imagemBTN.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        imagemBTN.setForeground(new java.awt.Color(255, 255, 255));
        imagemBTN.setText("SELECIONAR IMAGEM");
        imagemBTN.setToolTipText("Selecionar imagem");
        imagemBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemBTNActionPerformed(evt);
            }
        });

        desfazerImagem.setBackground(new java.awt.Color(153, 153, 153));
        desfazerImagem.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        desfazerImagem.setForeground(new java.awt.Color(255, 255, 255));
        desfazerImagem.setText("DESFAZER");
        desfazerImagem.setEnabled(false);
        desfazerImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desfazerImagemActionPerformed(evt);
            }
        });

        aleatorioCHK.setLabel("Alternativas Aleatorias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(aleatorioCHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(alt2vouf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                                            .addComponent(alt3vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alt4vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alt5vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alt6vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alt7vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alt1vouf))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alt1verdadeiro)
                                            .addComponent(alt2verdadeiro)
                                            .addComponent(alt3verdadeiro)
                                            .addComponent(alt4verdadeiro)
                                            .addComponent(alt5verdadeiro)
                                            .addComponent(alt6verdadeiro)
                                            .addComponent(alt7verdadeiro))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alt1falso)
                                    .addComponent(jLabel5)
                                    .addComponent(alt2falso)
                                    .addComponent(alt3falso)
                                    .addComponent(alt4falso)
                                    .addComponent(alt5falso)
                                    .addComponent(alt6falso)
                                    .addComponent(alt7falso))
                                .addGap(40, 40, 40))
                            .addComponent(enviarVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enunciadoVouF)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imagemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desfazerImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciadoVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(aleatorioCHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt1vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt1verdadeiro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt2vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt2verdadeiro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alt1falso)
                        .addGap(18, 18, 18)
                        .addComponent(alt2falso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt3vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt3verdadeiro)
                    .addComponent(alt3falso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt4vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt4verdadeiro)
                    .addComponent(alt4falso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt5vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt5verdadeiro)
                    .addComponent(alt5falso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt6vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt6verdadeiro)
                    .addComponent(alt6falso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt7falso)
                    .addComponent(alt7vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt7verdadeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(desfazerImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelImagem)
                            .addComponent(imagemBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeVouFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeVouFActionPerformed
        FormInicial home = new FormInicial();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeVouFActionPerformed

    private void enviarVouFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarVouFActionPerformed
        ConexaoBD conn = new ConexaoBD();
        ArrayList<String> erros = new ArrayList();
        ArrayList<Alternativa> alternativas = new ArrayList(5);
        VOuF verdadeiroFalso = new VOuF();
        
        
        if(disciplinaVouF.getSelectedIndex() == 0) erros.add("Disciplina não definida");
        if(temaVouF.getText().trim().equals("")) erros.add("Não ha temas definidos");
        if(dificuldadeVouF.getSelectedIndex() == 0) erros.add("Não ha dificuldade selecionada.");
        if(enunciadoVouF.getText().trim().equals("")) erros.add("Não ha enunciado definido");
        //Alternativas
        if(!(alt1vouf.getText().trim().isEmpty())
                && !(alt2vouf.getText().trim().isEmpty())){
           alternativas.add(new Alternativa(alt1vouf.getText().trim(),
            alt1verdadeiro.isSelected()));
           alternativas.add(new Alternativa(alt2vouf.getText().trim(), alt2verdadeiro.isSelected()));
           
           if(!(alt3vouf.getText().trim().isEmpty())){
               alternativas.add(new Alternativa(alt3vouf.getText().trim(), alt3verdadeiro.isSelected()));
           }
           
           if(!(alt4vouf.getText().trim().isEmpty())){
               alternativas.add(new Alternativa(alt4vouf.getText().trim(), alt4verdadeiro.isSelected()));
           }
           
           if(!(alt5vouf.getText().trim().isEmpty())){
               alternativas.add(new Alternativa(alt5vouf.getText().trim(), alt5verdadeiro.isSelected()));
           }
           
           if(!(alt6vouf.getText().trim().isEmpty())){
               alternativas.add(new Alternativa(alt6vouf.getText().trim(), alt6verdadeiro.isSelected()));
           }
           
           if(!(alt7vouf.getText().trim().isEmpty())){
               alternativas.add(new Alternativa(alt7vouf.getText().trim(), alt7verdadeiro.isSelected()));
           }
           
        } else {
            erros.add("Não ha alternativas suficientes definidas.");
        }
        if(erros.isEmpty()){
            verdadeiroFalso.setMateria(disciplinaVouF.getSelectedItem().toString());
            verdadeiroFalso.setConteudo(temaVouF.getText().trim().replace(" ", ""));
            verdadeiroFalso.setDificuldade((byte) dificuldadeVouF.getSelectedIndex());
            verdadeiroFalso.setEnunciado(enunciadoVouF.getText().trim());
            verdadeiroFalso.setAlternativas(alternativas);
            verdadeiroFalso.setAleatoria(aleatorioCHK.getState());
            if(!labelImagem.getText().equals("CAMINHO DA IMAGEM:")){
                verdadeiroFalso.setImagem(new Imagem(labelImagem.getText()));
            }
            
        try {
            if(editar){ //se for pra editar questão caso contrario insere
                    conn.editQuestaobd(idEditar, verdadeiroFalso);
                    JOptionPane.showMessageDialog(this, "Questão editada com sucesso "
                   + "no banco.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                } else { 
                conn.addQuestaobd(verdadeiroFalso);
            JOptionPane.showMessageDialog(this, "Questão adicionada com sucesso "
                    + "no banco.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de "
                    + "dados. Cheque sua conexão.", "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ERRO Ocorreu algum "
                    + "erro de input.", "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        }
         this.setVisible(false);
        new FormInicial().setVisible(true);
        } else{
            String errorList = "";
            for (String erro : erros) {
                errorList += erro + "\n";
            }
            JOptionPane.showMessageDialog(this, errorList, "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enviarVouFActionPerformed

    private void imagemBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemBTNActionPerformed
        if(seletorArq.showOpenDialog(jPanel1) == 1){
            JOptionPane.showMessageDialog(jPanel1, "Não foi selecionado nenum arquivo valido.");
        }else{
            labelImagem.setText(seletorArq.getSelectedFile().getAbsolutePath());

            desfazerImagem.setBackground(new Color(33,150,243));
            desfazerImagem.setEnabled(true);
        }
    }//GEN-LAST:event_imagemBTNActionPerformed

    private void desfazerImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desfazerImagemActionPerformed
        desfazerImagem.setBackground(new Color(153,153,153));
        desfazerImagem.setEnabled(false);

        labelImagem.setText("CAMINHO DA IMAGEM:");
    }//GEN-LAST:event_desfazerImagemActionPerformed

    private void temaVouFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temaVouFFocusGained
        if(temaVouF.getText().equals("DIGITE O TEXTO AQUI.")){
           temaVouF.setText("");
           temaVouF.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_temaVouFFocusGained

    private void enunciadoVouFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enunciadoVouFFocusGained
       if(enunciadoVouF.getText().equals("DIGITE O TEXTO AQUI.")){
           enunciadoVouF.setText("");
           enunciadoVouF.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_enunciadoVouFFocusGained

    private void alt1voufFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt1voufFocusGained
        if(alt1vouf.getText().equals("DIGITE O TEXTO AQUI.")){
           alt1vouf.setText("");
           alt1vouf.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alt1voufFocusGained

    private void alt2voufFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt2voufFocusGained
        if(alt2vouf.getText().equals("DIGITE O TEXTO AQUI.")){
           alt2vouf.setText("");
           alt2vouf.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alt2voufFocusGained

    private void alt3voufFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt3voufFocusGained
        if(alt3vouf.getText().equals("DIGITE O TEXTO AQUI.")){
           alt3vouf.setText("");
           alt3vouf.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alt3voufFocusGained

    private void alt4voufFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt4voufFocusGained
        if(alt4vouf.getText().equals("DIGITE O TEXTO AQUI.")){
           alt4vouf.setText("");
           alt4vouf.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alt4voufFocusGained

    private void alt5voufFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt5voufFocusGained
        if(alt5vouf.getText().equals("DIGITE O TEXTO AQUI.")){
           alt5vouf.setText("");
           alt5vouf.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alt5voufFocusGained

    private void alt6voufFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt6voufFocusGained
        if(alt6vouf.getText().equals("DIGITE O TEXTO AQUI.")){
           alt6vouf.setText("");
           alt6vouf.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alt6voufFocusGained

    private void alt7voufFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt7voufFocusGained
        if(alt7vouf.getText().equals("DIGITE O TEXTO AQUI.")){
           alt7vouf.setText("");
           alt7vouf.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_alt7voufFocusGained

    private void temaVouFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temaVouFFocusLost
        if(temaVouF.getText().equals("")){
            temaVouF.setText("DIGITE O TEXTO AQUI.");
            temaVouF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_temaVouFFocusLost

    private void enunciadoVouFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enunciadoVouFFocusLost
       if(enunciadoVouF.getText().equals("")){
            enunciadoVouF.setText("DIGITE O TEXTO AQUI.");
            enunciadoVouF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_enunciadoVouFFocusLost

    private void alt1voufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt1voufFocusLost
        if(alt1vouf.getText().equals("")){
            alt1vouf.setText("DIGITE O TEXTO AQUI.");
            alt1vouf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alt1voufFocusLost

    private void alt2voufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt2voufFocusLost
        if(alt2vouf.getText().equals("")){
            alt2vouf.setText("DIGITE O TEXTO AQUI.");
            alt2vouf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alt2voufFocusLost

    private void alt3voufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt3voufFocusLost
        if(alt3vouf.getText().equals("")){
            alt3vouf.setText("DIGITE O TEXTO AQUI.");
            alt3vouf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alt3voufFocusLost

    private void alt4voufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt4voufFocusLost
        if(alt4vouf.getText().equals("")){
            alt4vouf.setText("DIGITE O TEXTO AQUI.");
            alt4vouf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alt4voufFocusLost

    private void alt5voufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt5voufFocusLost
       if(alt5vouf.getText().equals("")){
            alt5vouf.setText("DIGITE O TEXTO AQUI.");
            alt5vouf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alt5voufFocusLost

    private void alt6voufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt6voufFocusLost
        if(alt6vouf.getText().equals("")){
            alt6vouf.setText("DIGITE O TEXTO AQUI.");
            alt6vouf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alt6voufFocusLost

    private void alt7voufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alt7voufFocusLost
        if(alt7vouf.getText().equals("")){
            alt7vouf.setText("DIGITE O TEXTO AQUI.");
            alt7vouf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_alt7voufFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirVouF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InserirVouF().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox aleatorioCHK;
    private javax.swing.JRadioButton alt1falso;
    private javax.swing.JRadioButton alt1verdadeiro;
    private javax.swing.JTextField alt1vouf;
    private javax.swing.JRadioButton alt2falso;
    private javax.swing.JRadioButton alt2verdadeiro;
    private javax.swing.JTextField alt2vouf;
    private javax.swing.JRadioButton alt3falso;
    private javax.swing.JRadioButton alt3verdadeiro;
    private javax.swing.JTextField alt3vouf;
    private javax.swing.JRadioButton alt4falso;
    private javax.swing.JRadioButton alt4verdadeiro;
    private javax.swing.JTextField alt4vouf;
    private javax.swing.JRadioButton alt5falso;
    private javax.swing.JRadioButton alt5verdadeiro;
    private javax.swing.JTextField alt5vouf;
    private javax.swing.JRadioButton alt6falso;
    private javax.swing.JRadioButton alt6verdadeiro;
    private javax.swing.JTextField alt6vouf;
    private javax.swing.JRadioButton alt7falso;
    private javax.swing.JRadioButton alt7verdadeiro;
    private javax.swing.JTextField alt7vouf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton desfazerImagem;
    private javax.swing.JComboBox<String> dificuldadeVouF;
    private javax.swing.JComboBox<String> disciplinaVouF;
    private javax.swing.JTextField enunciadoVouF;
    private javax.swing.JButton enviarVouF;
    private javax.swing.JButton homeVouF;
    private javax.swing.JButton imagemBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JFileChooser seletorArq;
    private javax.swing.JTextField temaVouF;
    // End of variables declaration//GEN-END:variables
}
