/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import bancodequestoes.ConexaoBD;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ThalesGSN
 */
public class Pesquisar extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    public Pesquisar() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Pesquisar.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        container = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homePesquisar = new javax.swing.JButton();
        enviarPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        disciplinasPesquisar = new javax.swing.JComboBox<>();
        materiaPesquisar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pesquisaPesquisar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setMaximumSize(new java.awt.Dimension(90, 99));
        Home.setMinimumSize(new java.awt.Dimension(90, 99));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 87, 155));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Banco de Questões");
        jLabel5.setToolTipText("Banco de Questões");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setAlignmentX(0.5F);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        homePesquisar.setBackground(new java.awt.Color(33, 150, 243));
        homePesquisar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        homePesquisar.setForeground(new java.awt.Color(255, 255, 255));
        homePesquisar.setText("HOME");
        homePesquisar.setToolTipText("Ir para  o inicio");
        homePesquisar.setAlignmentX(0.5F);
        homePesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePesquisarActionPerformed(evt);
            }
        });

        enviarPesquisar.setBackground(new java.awt.Color(33, 150, 243));
        enviarPesquisar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enviarPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        enviarPesquisar.setText("PESQUISAR QUESTÕES");
        enviarPesquisar.setToolTipText("Pesquisar");
        enviarPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Pesquise por um texto:");
        jLabel2.setToolTipText("Defina um um texto presente na questão");

        disciplinasPesquisar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        disciplinasPesquisar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina a disciplina:", "Aplicações para Web", "Arquitetura de Sistemas Digitais", "Linguagem de Programação - JAVA", "Manutenção de Computadores", "Biologia", "Filosofia", "Física", "Geografia", "História", "Matemática", "Português", "Química", "Sociologia", "Outra" }));
        disciplinasPesquisar.setToolTipText("Defina a disciplina:");

        materiaPesquisar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        materiaPesquisar.setForeground(new java.awt.Color(153, 153, 153));
        materiaPesquisar.setText("DIGITE O TEXTO AQUI.");
        materiaPesquisar.setToolTipText("Defina a materia da questão");
        materiaPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                materiaPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                materiaPesquisarFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Selecione a matéria:");
        jLabel3.setToolTipText("Defina a materia da questão");

        pesquisaPesquisar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pesquisaPesquisar.setForeground(new java.awt.Color(153, 153, 153));
        pesquisaPesquisar.setText("DIGITE O TEXTO AQUI.");
        pesquisaPesquisar.setToolTipText("Defina um um texto presente na questão");
        pesquisaPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pesquisaPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesquisaPesquisarFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disciplinasPesquisar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(materiaPesquisar))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesquisaPesquisar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(enviarPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(homePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disciplinasPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materiaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(enviarPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("A ferramenta que produz provas de maneira simples e funcional");
        jLabel6.setToolTipText("Descrição");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        container.add(Home, "Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePesquisarActionPerformed
        FormInicial home = new FormInicial();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homePesquisarActionPerformed

    private void enviarPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarPesquisarActionPerformed
       ConexaoBD conn = new ConexaoBD();
       
       if(disciplinasPesquisar.getSelectedItem().toString().equals("Defina a disciplina:" )
               && materiaPesquisar.getText().trim().equals("DIGITE O TEXTO AQUI.") 
               && pesquisaPesquisar.getText().trim().equals("DIGITE O TEXTO AQUI.")){
           JOptionPane.showMessageDialog(this, " Essa"
                       + "não é uma pesquisa valida,", "ERRO",
                    JOptionPane.ERROR_MESSAGE);
       } else {
       
        try {
            String disciplinas = null;
            String materia = null;
            String pesquisa = null;
            if(!disciplinasPesquisar.getSelectedItem().toString().equals("Defina a disciplina:")){
                disciplinas = disciplinasPesquisar.getSelectedItem().toString();
            }
            if(!materiaPesquisar.getText().trim().equals("DIGITE O TEXTO AQUI.")){
                materia = materiaPesquisar.getText().trim();
            }
            if(!pesquisaPesquisar.getText().trim().equals("DIGITE O TEXTO AQUI.")){
                pesquisa =  pesquisaPesquisar.getText().trim();
            }
          Tabela pesquiTabela = new Tabela(conn.pesquisarQuestoes(disciplinas, materia,  pesquisa));
          this.setVisible(false);
          pesquiTabela.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de "
                    + "dados. Cheque sua conexão.", "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        }
       }
    }//GEN-LAST:event_enviarPesquisarActionPerformed

    private void materiaPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_materiaPesquisarFocusGained
         if(materiaPesquisar.getText().equals("DIGITE O TEXTO AQUI.")){
           materiaPesquisar.setText("");
           materiaPesquisar.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_materiaPesquisarFocusGained

    private void pesquisaPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisaPesquisarFocusGained
         if(pesquisaPesquisar.getText().equals("DIGITE O TEXTO AQUI.")){
           pesquisaPesquisar.setText("");
           pesquisaPesquisar.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_pesquisaPesquisarFocusGained

    private void materiaPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_materiaPesquisarFocusLost
        if(materiaPesquisar.getText().equals("")){
            materiaPesquisar.setText("DIGITE O TEXTO AQUI.");
            materiaPesquisar.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_materiaPesquisarFocusLost

    private void pesquisaPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisaPesquisarFocusLost
        if(pesquisaPesquisar.getText().equals("")){
            pesquisaPesquisar.setText("DIGITE O TEXTO AQUI.");
            pesquisaPesquisar.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_pesquisaPesquisarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pesquisar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel container;
    private javax.swing.JComboBox<String> disciplinasPesquisar;
    private javax.swing.JButton enviarPesquisar;
    private javax.swing.JButton homePesquisar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField materiaPesquisar;
    private javax.swing.JTextField pesquisaPesquisar;
    // End of variables declaration//GEN-END:variables
}
