/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Aluno
 */
public class ContainerGigante extends javax.swing.JPanel {

    /**
     * Creates new form ContainerGigante
     */
    public ContainerGigante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        provaOff2 = new main.ProvaOff();
        interfacePrincipal1 = new main.InterfacePrincipal();
        provaOff3 = new main.ProvaOff();
        panelCorrecao2 = new main.PanelCorrecao();

        setLayout(new java.awt.CardLayout());
        add(interfacePrincipal1, "InterfacePrincipal");
        add(provaOff3, "ProvaOff");
        add(panelCorrecao2, "PanelCorrecao");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.InterfacePrincipal interfacePrincipal1;
    private main.PanelCorrecao panelCorrecao2;
    private main.ProvaOff provaOff2;
    private main.ProvaOff provaOff3;
    // End of variables declaration//GEN-END:variables
}
